plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1, PSR2, PHPCS"
  phpmd:
    enable: true
    config:
      file_extensions:
        - php
      rulesets: "unusedcode,naming"
